import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import * as engine from '../dist/engine.js';
import * as journey from '../dist/journey.js';
import * as crossword from '../dist/crossword.js';
import * as catalog from '../dist/catalog.js';
import * as wordsearch from '../dist/wordsearch.js';
import * as curriculum from '../dist/curriculum.js';
import * as migration from '../dist/migration.js';
class Element{
 constructor(){this.hidden=false;this.open=false;this.value='12';this._html='';this.textContent='';this.dataset={};this.style={setProperty:(k,v)=>this.style[k]=v};const set=new Set();this.classList={add:(...xs)=>xs.forEach(x=>set.add(x)),remove:(...xs)=>xs.forEach(x=>set.delete(x)),toggle:(x,b)=>{if(b===undefined)b=!set.has(x);b?set.add(x):set.delete(x);},contains:x=>set.has(x)};this.listeners={};}
 set innerHTML(s){this._html=s;}get innerHTML(){return this._html;}showModal(){this.open=true;}close(){this.open=false;}addEventListener(n,f){this.listeners[n]=f;}focus(){}
}
function setup(width=390,height=844){const el=new Map(),docEvents={},events={},pending=new Map(),intervals=new Map();let id=0;const get=s=>{if(s==='#modal-content .count'&&!get('#modal-content').innerHTML.includes('class="count"'))return null;if(!el.has(s))el.set(s,new Element());return el.get(s);};const body=new Element(),nav=['home','fighters','powers','rewards'].map(action=>{const x=new Element();x.dataset.action=action;return x;});const document={querySelector:get,querySelectorAll:s=>s==='.bottom-nav button'?nav:[],body,hidden:false,addEventListener:(n,f)=>docEvents[n]=f};const storage=new Map();class Audio{constructor(src){this.src=src;this.paused=true;}play(){this.paused=false;return Promise.resolve();}pause(){this.paused=true;}}
 const context=vm.createContext({...engine,...journey,...crossword,...catalog,...wordsearch,...curriculum,...migration,document,window:{scrollTo(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},Audio,innerWidth:width,innerHeight:height,Math,console,setTimeout:(f)=>{pending.set(++id,f);return id;},clearTimeout:id=>pending.delete(id),setInterval:f=>{intervals.set(++id,f);return id;},clearInterval:id=>intervals.delete(id),addEventListener:(n,f)=>events[n]=f});
 const source=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'');vm.runInContext(source,context);
 const run=s=>vm.runInContext(s,context),click=(action,data={})=>{const button={dataset:{action,...data},disabled:false};docEvents.click({target:{closest:()=>button}});};const advance=(limit=20)=>{let n=0;while(pending.size&&n++<limit){const [key,f]=pending.entries().next().value;pending.delete(key);f();}};
 return {get,body,document,docEvents,events,run,click,advance,pending,intervals,context};
}
test('every home destination opens functional content',()=>{const h=setup();for(const [action,text] of [['fighters','Green Hopper'],['powers','Frog Vision'],['rewards','Frog Trophy Trail'],['records','Personal Bests'],['holidays','Halloween Pond'],['leagues','Eggs: A New Beginning']]){h.click(action);assert.ok(h.get('#hub-content').innerHTML.includes(text),action);}h.click('home');assert.equal(h.get('#home').hidden,false);h.click('choose-fighter',{id:'blue'});assert.equal(h.run('p.selected'),'green');});
test('practice countdown leads to playable cards and a rewarded finish',()=>{const h=setup();h.click('practice');h.click('start',{id:'solo'});h.advance(4);assert.equal(h.get('#modal').open,false);assert.equal(h.run('match.mode'),'solo');assert.equal(h.get('#game').hidden,false);assert.equal(h.get('#timer').textContent,'∞');for(let k=0;k<6;k++){const pair=h.run(`(()=>{const a=match.deck.findIndex(c=>!c.matched);const b=match.deck.findIndex((c,i)=>i!==a&&!c.matched&&c.value===match.deck[a].value);return [a,b]})()`);h.click('card',{index:String(pair[0])});h.click('card',{index:String(pair[1])});h.advance(1);}assert.equal(h.run('p.wins'),1);assert.equal(h.run('p.rivalWins'),0);assert.ok(h.get('#modal-content').innerHTML.includes('YOU WON!'));assert.ok(h.get('#modal-content').innerHTML.includes('100% accuracy'));});
test('rematch retains rival, best-of-three finishes after two wins',()=>{const h=setup();h.click('play');h.click('start',{id:'rival'});h.advance(4);const name=h.run('series.rival');h.run("match.done=true;match.pairs=4;match.attempts=5;match.scores={you:4,rival:2};finish();");assert.ok(h.get('#modal-content').innerHTML.includes('Rematch?'));h.click('rematch');h.advance(4);assert.equal(h.run('series.rival'),name);assert.equal(h.run('series.you'),1);h.run("match.done=true;match.pairs=4;match.attempts=5;match.scores={you:4,rival:2};finish();");assert.ok(h.get('#modal-content').innerHTML.includes('SHOWDOWN WON!'));assert.ok(h.get('#modal-content').innerHTML.includes('Best-of-three victory: +10 frogs'));});
test('leaving and hiding cancels pending gameplay and creates a fresh rival',()=>{const h=setup();h.click('play');h.click('start',{id:'rival'});h.advance(4);const name=h.run('series.rival');h.document.hidden=true;h.docEvents.visibilitychange();assert.equal(h.run('match'),null);assert.equal(h.intervals.size,0);h.advance(10);assert.equal(h.get('#home').hidden,false);h.document.hidden=false;h.click('play');h.click('start',{id:'rival'});assert.notEqual(h.run('series.rival'),name);h.click('home');h.advance(10);assert.equal(h.get('#modal').open,false);});
test('phone portrait, landscape, small phone and desktop choose fitting card columns',()=>{for(const [w,he,cols] of [[390,844,4],[844,390,6],[320,568,4],[1366,768,6]]){const h=setup(w,he);h.click('practice');h.click('start',{id:'solo'});h.advance(4);assert.equal(h.get('#board').style['--cols'],cols);assert.equal((h.get('#board').innerHTML.match(/data-action="card"/g)||[]).length,12);}});
test('championship win advances only its event and uses the seasonal decoration',()=>{const h=setup();h.click('championship',{id:'halloween'});h.click('start',{id:'rival'});h.advance(4);assert.ok(h.body.classList.contains('theme-halloween'));h.run("match.done=true;match.pairs=4;match.attempts=5;match.scores={you:4,rival:2};finish();");assert.equal(h.run('p.season.halloween'),1);assert.equal(h.run('p.season.winter'),0);});
test('journey round offers a learning check, wrong answer retries, correct answer saves once',()=>{const h=setup();h.click('learn-next');h.advance(4);assert.ok(h.run("match.deck.every(c=>c.value.includes('|'))"));h.run("match.done=true;match.pairs=6;match.attempts=6;finish();");assert.ok(h.get('#modal-content').innerHTML.includes('Discover & Learn'));h.click('learning-check');h.click('learning-answer',{index:'2'});assert.equal(h.run('p.journey.learned.length'),0);assert.ok(h.get('#learning-feedback').textContent.includes('try again'));h.click('learning-answer',{index:'0'});assert.equal(h.run('p.journey.learned.length'),1);const bank=h.run('p.bank');h.click('learning-answer',{index:'0'});assert.equal(h.run('p.bank'),bank);});
test('winning solo round launches next stage rather than repeating 12 cards',()=>{const h=setup();h.click('practice');h.click('start',{id:'solo'});h.advance(4);h.run('match.done=true;match.pairs=6;match.attempts=6;finish();');assert.equal(h.run('p.stage'),18);assert.ok(h.get('#modal-content').innerHTML.includes('Next Stage · 18 cards'));h.click('again');h.advance(4);assert.equal(h.run('match.deck.length'),18);});
test('crossword mode opens clues, rewards a solve, and advances to the next puzzle',()=>{const h=setup();h.click('crossword');assert.ok(h.get('#hub-content').innerHTML.includes('Nature Puzzle 1'));assert.ok(h.get('#hub-content').innerHTML.includes('Across'));h.run("p.crossword.letters=Object.fromEntries([...puzzle.cells].map(([key,c])=>[key,c.letter]));");h.click('crossword-check');assert.equal(h.run('p.crossword.level'),2);assert.ok(h.get('#modal-content').innerHTML.includes('POND PUZZLE SOLVED!'));h.click('puzzle-check');h.click('puzzle-answer',{index:String(h.run('LESSONS.find(l=>l.id===p.puzzleLearning.pending.lessonId).answer'))});h.click('crossword');assert.ok(h.get('#hub-content').innerHTML.includes('Nature Puzzle 2'));});
test('learning bank and next collection render without losing owned fighters',()=>{const h=setup();h.click('bank');assert.ok(h.get('#hub-content').innerHTML.includes('19 discoveries'));h.run('p.owned=FIGHTERS.slice(0,9).map(f=>f.id)');h.click('fighters');h.click('collection-next');assert.ok(h.get('#hub-content').innerHTML.includes('Fighter Collection 2'));h.run('p.bank=1000');h.click('choose-fighter',{id:'collectible-0'});assert.equal(h.run('p.selected'),'collectible-0');assert.ok(h.get('#hub-content').innerHTML.includes('Selected'));});
test('all ten added powers activate, consume once, and keep inventory for unavailable actions',()=>{for(const id of ['clock','link','spotlight','safe','shield','harvest','recall','shuffle','lantern','echo']){const h=setup();h.click('play');h.click('start',{id:'rival'});h.advance(4);h.run(`p.inventory['${id}']=1`);if(id==='recall')h.run('match.lastMismatch=[0,1]');h.click('use-power',{id});assert.equal(h.run(`p.inventory['${id}']`),0,id);if(['link','spotlight','recall','lantern'].includes(id)){assert.ok(h.run('peek.length>0'),id);h.advance(1);assert.equal(h.run('match.lock'),false);}if(id==='clock')assert.equal(h.get('#timer').textContent,20);if(id==='echo')assert.equal(h.run('match.echo'),2);if(['safe','shield','harvest'].includes(id))assert.equal(h.run(`match['${id}']`),true);}});
test('word-search tapping finds saved words, completes a puzzle, and opens next level',()=>{const h=setup();h.click('wordsearch');assert.ok(h.get('#hub-content').innerHTML.includes('Puzzle 1'));const placements=h.run('searchPuzzle.placements');for(const w of placements){h.click('search-cell',{row:String(w.r),col:String(w.c)});h.click('search-cell',{row:String(w.r+w.dr*(w.word.length-1)),col:String(w.c+w.dc*(w.word.length-1))});}assert.equal(h.run('p.wordSearch.level'),2);assert.equal(h.run('p.bank'),40);assert.ok(h.get('#modal-content').innerHTML.includes('NATURE WORDS FOUND!'));h.click('puzzle-check');h.click('puzzle-answer',{index:String(h.run('LESSONS.find(l=>l.id===p.puzzleLearning.pending.lessonId).answer'))});h.click('wordsearch');assert.ok(h.get('#hub-content').innerHTML.includes('Puzzle 2'));});

test('optional puzzle checks can be skipped, and clues help without charging frogs',()=>{const h=setup();h.click('crossword');const bank=h.run('p.bank');h.click('crossword-hint');assert.ok(h.run('Object.keys(p.crossword.letters).length')>0);assert.equal(h.run('p.bank'),bank);h.run("p.crossword.letters=Object.fromEntries([...puzzle.cells].map(([key,c])=>[key,c.letter]));");h.click('crossword-check');assert.ok(h.run('p.puzzleLearning.pending'));h.click('skip-puzzle-check');assert.equal(h.run('p.puzzleLearning.pending'),null);assert.equal(h.run('p.puzzleLearning.checks'),0);assert.equal(h.run('p.journey.learned.length'),0);assert.equal(h.run('puzzle.level'),2);h.click('home');h.click('wordsearch');h.click('wordsearch-hint');assert.ok(h.run('searchStart'));assert.ok(h.get('#wordsearch-feedback').textContent.includes('highlighted'));});
test('life-cycle ordering gives helpful retries and pays once after four stages',()=>{const h=setup();h.click('cycle');const bank=h.run('p.bank');h.click('cycle-stage',{index:'2'});assert.ok(h.get('#cycle-feedback').textContent.includes('Try again'));assert.equal(h.run('p.bank'),bank);for(const i of [0,1,2,3])h.click('cycle-stage',{index:String(i)});assert.equal(h.run('p.bank'),bank+2);assert.equal(h.run('p.puzzleLearning.cycleRounds'),1);h.click('cycle-stage',{index:'3'});assert.equal(h.run('p.bank'),bank+2);h.click('healthy-pond');assert.ok(h.get('#hub-content').innerHTML.includes('food web'));});
test('Deep Dive reasoning questions mark correct answers and preserve Journey progress',()=>{const h=setup();h.click('learning-pace',{id:'challenge'});assert.equal(h.run('p.settings.learning'),'challenge');h.click('wordsearch');const placements=h.run('searchPuzzle.placements');for(const w of placements){h.click('search-cell',{row:String(w.r),col:String(w.c)});h.click('search-cell',{row:String(w.r+w.dr*(w.word.length-1)),col:String(w.c+w.dc*(w.word.length-1))});}h.click('puzzle-check');assert.ok(h.get('#modal-content').innerHTML.includes('rather than a rule'));const answer=h.run('learningPrompt(p,LESSONS.find(l=>l.id===p.puzzleLearning.pending.lessonId)).answer');h.click('puzzle-answer',{index:String((answer+1)%3)});assert.equal(h.run('p.puzzleLearning.checks'),0);h.click('puzzle-answer',{index:String(answer)});assert.equal(h.run('p.puzzleLearning.checks'),1);assert.equal(h.run('p.journey.learned.length'),1);});

test('spoken countdown plays the uploaded clip and stops when leaving; muted effects stay silent',()=>{const h=setup();h.click('practice');h.click('start',{id:'solo'});assert.equal(h.run('countdownAudio.src'),'assets/countdown-voice.mp3');assert.equal(h.run('countdownAudio.paused'),false);h.click('home');assert.equal(h.run('countdownAudio.paused'),true);const m=setup();m.run('p.settings.sound=false');m.click('practice');m.click('start',{id:'solo'});assert.equal(m.run('countdownAudio'),null);m.advance(4);assert.equal(m.get('#modal').open,false);});

test('matching power chooser preserves remaining turn time and returns to a playable board',()=>{const h=setup();h.click('play');h.click('start',{id:'rival'});h.advance(4);h.run("p.inventory.double=1;seconds=8");h.click('match-powers');assert.equal(h.get('#modal').open,true);assert.ok(h.get('#modal-content').innerHTML.includes('Double Hopper'));h.click('use-power',{id:'double'});assert.equal(h.get('#modal').open,false);assert.equal(h.run('seconds'),8);assert.equal(h.run('p.inventory.double'),0);assert.equal(h.run('match.double'),true);});
test('play menus provide player and power choices; opening a collection dismisses the menu',()=>{const h=setup();h.click('play');assert.ok(h.get('#modal-content').innerHTML.includes('Pick A Player'));assert.ok(h.get('#modal-content').innerHTML.includes('Pick Your Super Powers'));h.click('fighters');assert.equal(h.get('#modal').open,false);assert.equal(h.get('#hub').hidden,false);});
test('puzzle discovery, word list and crossword clues open separate readable views',()=>{const h=setup();h.click('wordsearch');h.click('puzzle-discovery');assert.ok(h.get('#modal-content').innerHTML.includes('Today’s Discovery'));h.click('close-reading');h.click('search-words');assert.ok(h.get('#modal-content').innerHTML.includes('Nature Words'));h.click('close-reading');h.click('crossword');h.click('crossword-clues');assert.ok(h.get('#modal-content').innerHTML.includes('Across & Down Clues'));const id=h.run('puzzle.entries[1].id');h.click('crossword-clue',{id:String(id)});assert.equal(h.get('#modal').open,false);assert.equal(h.run('activeEntry.id'),id);});
test('home keeps Rival and Solo bars and gives four other destinations circular buttons',()=>{const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');const home=html.match(/<section id="home"[\s\S]*?<\/section>/)[0];assert.ok(home.includes('class="play-bars"'));assert.ok(home.includes('data-action="play"'));assert.ok(home.includes('data-action="practice"'));const bubbles=home.match(/<nav class="game-bubbles"[\s\S]*?<\/nav>/)[0];for(const action of ['journey','explore','crossword','wordsearch'])assert.ok(bubbles.includes(`data-action="${action}"`));assert.equal((bubbles.match(/<button /g)||[]).length,4);});

test('spoken countdown follows actual audio time, including delayed playback and stalls',()=>{const h=setup();h.click('practice');h.click('start',{id:'solo'});h.run('countdownAudio.currentTime=0;countdownAudio.onplaying();');assert.equal(h.get('#modal-content .count').textContent,'3');assert.equal(h.get('#modal').open,true);for(const [time,label] of [[1.4,'2'],[1.4,'2'],[2.5,'1'],[3.9,'GO!']]){h.run(`countdownAudio.currentTime=${time};countdownAudio.ontimeupdate();`);assert.equal(h.get('#modal-content .count').textContent,label);assert.equal(h.get('#modal').open,true);}h.run('countdownAudio.onended();');assert.equal(h.get('#modal').open,false);assert.equal(h.get('#timer').textContent,'∞');});
test('leaving during countdown disables stale audio callbacks',()=>{const h=setup();h.click('practice');h.click('start',{id:'solo'});h.run('countdownAudio.onplaying();');const ended=h.run('countdownAudio.onended');h.click('home');ended();assert.equal(h.run('match'),null);assert.equal(h.get('#home').hidden,false);assert.equal(h.get('#modal').open,false);});

test('card taps reuse buttons and request geometry only when the board size changes',()=>{
 const h=setup();h.click('practice');h.click('start',{id:'solo'});h.advance(4);
 const board=h.get('#board'),cards=Array.from({length:12},()=>({className:'card',disabled:false,innerHTML:'🪷',label:'',getAttribute(){return this.label;},setAttribute(k,v){this.label=v;}}));
 board.querySelectorAll=()=>cards;let layouts=0;h.context.window.frogFitBoard=()=>layouts++;
 h.run('renderBoard()');const before=board.innerHTML;
 h.click('card',{index:'0'});
 assert.equal(board.innerHTML,before,'tap does not rebuild the board');
 assert.notEqual(cards[0].innerHTML,'🪷');assert.equal(layouts,0);
 h.run("match=new Match({mode:'solo',cards:18});renderBoard()");assert.equal(layouts,1);
});
