import test from 'node:test';
import assert from 'node:assert/strict';
import {Match,freshProfile,loadProfile,settle,leagueFor,makeDeck,STAGES,stageAvailable} from '../dist/engine.js';
function completed(mode='rival',win=true){const m=new Match({mode});m.done=true;m.pairs=4;m.attempts=6;m.scores={you:win?4:2,rival:win?2:4};return m;}
test('all stages contain exactly two of each animal, through 52 cards',()=>{for(const n of STAGES){const deck=makeDeck(n);assert.equal(deck.length,n);const counts=new Map();deck.forEach(c=>counts.set(c.value,(counts.get(c.value)||0)+1));assert.equal(counts.size,n/2);assert.ok([...counts.values()].every(n=>n===2));}});
test('mismatch remains visible until resolution and changes rival turn',()=>{const m=new Match();const a=0,b=m.deck.findIndex(c=>c.value!==m.deck[a].value);assert.equal(m.select(a).type,'first');assert.equal(m.select(a).type,'ignored');assert.equal(m.select(b).type,'mismatch');assert.equal(m.revealed.length,2);assert.equal(m.select(2).type,'ignored');assert.equal(m.resolve(false),'rival');assert.deepEqual(m.revealed,[]);assert.equal(m.attempts,1);});
test('matching pair keeps turn, awards points, and cannot be selected again',()=>{const m=new Match();const a=0,b=m.deck.findIndex((c,i)=>i!==a&&c.value===m.deck[a].value);m.double=true;m.select(a);assert.equal(m.select(b).type,'match');assert.equal(m.scores.you,3);assert.equal(m.pairs,1);assert.equal(m.double,false);m.resolve(true);assert.equal(m.turn,'you');assert.equal(m.select(a).type,'ignored');});
test('freeze skips exactly one CPU turn, solo never hands turn to rival',()=>{const m=new Match();m.freeze=true;m.nextTurn();assert.equal(m.turn,'you');assert.equal(m.freeze,false);m.nextTurn();assert.equal(m.turn,'rival');const solo=new Match({mode:'solo'});solo.nextTurn();assert.equal(solo.turn,'you');});
test('CPU uses only exposed memory, known pair can be chosen',()=>{const m=new Match({rng:()=>.1});const a=0,b=m.deck.findIndex((c,i)=>i!==a&&c.value===m.deck[a].value);m.turn='rival';m.memory.set(a,m.deck[a].value);m.memory.set(b,m.deck[b].value);assert.equal(m.botChoice(),a);m.select(a,'rival');assert.equal(m.botChoice(),b);});
test('settlement awards currency once and never rewards unfinished games',()=>{const p=freshProfile(),m=completed();const result=settle(p,m);assert.equal(result.currency,23);assert.equal(p.bank,43);assert.equal(p.wins,1);assert.equal(p.rivalWins,1);assert.equal(settle(p,m),null);assert.equal(settle(p,new Match()),null);assert.equal(p.bank,43);});
test('trail has five milestones, grants currency once, unlocks special frog',()=>{const p=freshProfile();for(let i=0;i<12;i++)settle(p,completed('solo'));assert.deepEqual(p.trail,[0,1,2,3,4]);assert.ok(p.owned.includes('trail-gold'));assert.equal(p.rivalWins,0);assert.equal(p.bank,20+12*13+160);settle(p,completed('solo'));assert.equal(p.owned.filter(x=>x==='trail-gold').length,1);});
test('league threshold and promotion progress are accurate',()=>{assert.equal(leagueFor(0).remaining,3);assert.equal(leagueFor(1).remaining,2);assert.equal(leagueFor(3).current.name,'Lily Pond');assert.equal(leagueFor(3).progress,0);assert.equal(leagueFor(25).current.name,'Golden Pond');assert.equal(leagueFor(25).remaining,0);});
test('seasonal costumes require five rival wins and pay only once',()=>{const p=freshProfile();for(let i=0;i<5;i++)settle(p,completed(),'halloween');assert.ok(p.owned.includes('pumpkin'));assert.ok(!p.owned.includes('snowflake'));assert.equal(p.season.halloween,5);const before=p.bank;settle(p,completed(),'halloween');assert.equal(p.bank-before,13);for(let i=0;i<5;i++)settle(p,completed(),'winter');assert.ok(p.owned.includes('snowflake'));assert.deepEqual(p.seasonClaimed,['halloween','winter']);});
test('loss and tie do not advance leagues or seasonal wins',()=>{const p=freshProfile();settle(p,completed('rival',false),'winter');const m=completed();m.scores={you:3,rival:3};settle(p,m,'winter');assert.equal(p.wins,0);assert.equal(p.rivalWins,0);assert.equal(p.season.winter,0);});
test('personal bests only improve on completed wins',()=>{const p=freshProfile(),m=completed();m.maxDeficit=3;settle(p,m);assert.equal(p.records.accuracy,67);assert.equal(p.records.comeback,3);assert.equal(p.records.cards,12);const loss=completed('rival',false);loss.maxDeficit=8;settle(p,loss);assert.equal(p.records.comeback,3);assert.equal(stageAvailable(p,18),true);settle(p,completed());assert.equal(stageAvailable(p,18),true);});
test('profile persistence round trip and corrupted data recovery',()=>{const p=freshProfile();p.bank=72;p.owned.push('pumpkin');p.selected='pumpkin';p.season.halloween=5;const loaded=loadProfile(JSON.stringify(p));assert.equal(loaded.bank,72);assert.equal(loaded.selected,'pumpkin');assert.equal(loaded.season.halloween,5);assert.deepEqual(loadProfile('{bad'),freshProfile());assert.equal(loadProfile(JSON.stringify({...p,bank:-4,selected:'fake'})).bank,20);});

test('completed losses advance playable stages without awarding a win',()=>{const p=freshProfile();settle(p,completed('rival',false));assert.equal(p.stage,18);assert.equal(stageAvailable(p,18),true);assert.equal(p.wins,0);const loaded=loadProfile(JSON.stringify(p));assert.equal(stageAvailable(loaded,18),true);});
test('CPU memory is limited to six exposed cards and can forget a known pair',()=>{const m=new Match({mode:'solo'});for(let i=0;i<8;i++){m.revealed=[];m.lock=false;m.select(i);}assert.ok(m.memory.size<=6);assert.equal(m.memory.has(0),false);const n=new Match({rng:()=>.5});n.memory.set(0,n.deck[0].value);const pair=n.deck.findIndex((c,i)=>i!==0&&c.value===n.deck[0].value);n.memory.set(pair,n.deck[pair].value);assert.equal(n.botChoice(),6);});
