import test from 'node:test';
import assert from 'node:assert/strict';
import {FIGHTERS,POWERS,freshProfile,loadProfile,Match,settle} from '../dist/engine.js';
import {collectionPageUnlocked,highestCollectionPage} from '../dist/catalog.js';
function pair(m){const a=m.deck.findIndex(c=>!c.matched),b=m.deck.findIndex((c,i)=>i!==a&&!c.matched&&c.value===m.deck[a].value);m.select(a);return m.select(b);}
function win(){const m=new Match({mode:'solo'});m.done=true;m.pairs=6;m.attempts=6;return m;}
test('261 unique cosmetic fighters form 29 sets of nine, with sequential unlocks',()=>{const p=freshProfile();assert.equal(FIGHTERS.length,261);assert.equal(new Set(FIGHTERS.map(f=>f.id)).size,261);assert.equal(new Set(FIGHTERS.map(f=>f.name)).size,261);assert.equal(collectionPageUnlocked(p,FIGHTERS,1),false);p.owned=FIGHTERS.slice(0,8).map(f=>f.id);assert.equal(highestCollectionPage(p,FIGHTERS),0);p.owned.push(FIGHTERS[8].id);assert.equal(highestCollectionPage(p,FIGHTERS),1);p.owned=FIGHTERS.slice(0,18).map(f=>f.id);assert.equal(highestCollectionPage(p,FIGHTERS),2);p.selected=FIGHTERS[17].id;assert.equal(loadProfile(JSON.stringify(p)).selected,p.selected);});
test('trophy trails continue past the first five stops without repaying earlier milestones',()=>{const p=freshProfile();for(let i=0;i<36;i++)settle(p,win());assert.equal(p.trail.length,15);assert.ok(p.owned.includes('trail-gold'));assert.ok(p.owned.includes(FIGHTERS[10].id));assert.ok(p.owned.includes(FIGHTERS[19].id));const q=loadProfile(JSON.stringify(p));assert.equal(q.trail.length,15);const bank=q.bank;settle(q,win());assert.equal(q.bank-bank,17+25);});
test('soft landing keeps one turn after mismatch; shield blocks one CPU score',()=>{const m=new Match();m.safe=true;const a=0,b=m.deck.findIndex(c=>c.value!==m.deck[a].value);m.select(a);m.select(b);m.resolve(false);assert.equal(m.turn,'you');assert.equal(m.safe,false);m.shield=true;m.turn='rival';const x=m.deck.findIndex(c=>!c.matched),y=m.deck.findIndex((c,i)=>i!==x&&c.value===m.deck[x].value);m.select(x,'rival');m.select(y,'rival');assert.equal(m.scores.rival,0);assert.equal(m.shield,false);});
test('Echo Hopper and Fly Harvest apply to the intended number of pairs and settle once',()=>{const p=freshProfile(),m=new Match({mode:'solo'});m.echo=2;m.harvest=true;pair(m);m.resolve(true);assert.equal(m.scores.you,2);assert.equal(m.bonusCurrency,3);pair(m);m.resolve(true);assert.equal(m.scores.you,4);pair(m);m.resolve(true);assert.equal(m.scores.you,5);m.done=true;const result=settle(p,m);assert.equal(result.currency,24);assert.ok(result.rewards.some(s=>s.includes('Fly Harvest')));assert.equal(settle(p,m),null);});
test('power catalog has 15 distinct priced powers',()=>{assert.equal(POWERS.length,15);assert.equal(new Set(POWERS.map(p=>p.id)).size,15);assert.ok(POWERS.every(p=>p.price>0&&p.desc));});
